[project]
name = "swadesh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "pandas>=3.0.0",
    "unidecode>=1.4.0",
]
